controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    trj0_controller:
      type: effort_controllers/JointPositionController

    trj1_controller:
      type: effort_controllers/JointPositionController

    wheel_controller:
      type: velocity_controllers/JointGroupVelocityController

trj0_controller:
  ros__parameters:
    joints:
      - trj0
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    gains:
      trj0:
        p: 50.0
        i: 0.0
        d: 1.0

trj1_controller:
  ros__parameters:
    joints:
      - trj1
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    gains:
      trj1:
        p: 50.0
        i: 0.0
        d: 1.0

wheel_controller:
  ros__parameters:
    joints:
      - whj0
      - whj1
      - whj2
      - whj3
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity